# Generated by Django 2.2.3 on 2019-09-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0030_grant_clr_prediction_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='defer_clr_to',
            field=models.ForeignKey(help_text='The Grant that this grant defers it CLR contributions to (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defered_clr_to', to='grants.Grant'),
        ),
    ]
